from __future__ import annotations

from iris_bot.config_runtime import env_source, load_settings, validate_config
from iris_bot.config_types import (
    ApprovedDemoGateConfig,
    BacktestConfig,
    ChaosConfig,
    DataConfig,
    DemoExecutionConfig,
    DynamicExitConfig,
    EnduranceConfig,
    ExitPolicyRuntimeConfig,
    ExperimentConfig,
    GovernanceConfig,
    LabelingConfig,
    LifecycleConfig,
    LoggingConfig,
    MT5Config,
    OperationalConfig,
    ReconciliationConfig,
    RecoveryConfig,
    RiskConfig,
    SessionConfig,
    SignificanceConfig,
    Settings,
    SoakConfig,
    SplitConfig,
    StrategyConfig,
    ThresholdConfig,
    TradingConfig,
    WalkForwardConfig,
    XGBoostConfig,
)


settings = load_settings()


__all__ = [
    "ApprovedDemoGateConfig",
    "BacktestConfig",
    "ChaosConfig",
    "DataConfig",
    "DemoExecutionConfig",
    "DynamicExitConfig",
    "EnduranceConfig",
    "ExitPolicyRuntimeConfig",
    "ExperimentConfig",
    "GovernanceConfig",
    "LabelingConfig",
    "LifecycleConfig",
    "LoggingConfig",
    "MT5Config",
    "OperationalConfig",
    "ReconciliationConfig",
    "RecoveryConfig",
    "RiskConfig",
    "SessionConfig",
    "SignificanceConfig",
    "Settings",
    "SoakConfig",
    "SplitConfig",
    "StrategyConfig",
    "ThresholdConfig",
    "TradingConfig",
    "WalkForwardConfig",
    "XGBoostConfig",
    "env_source",
    "load_settings",
    "settings",
    "validate_config",
]
